baseURL                   = "https://www.angyi.online/"
builddrafts                = false
languageCode               = "zn-Hans"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 5

theme                      = "AllinOne"
title                      = "Angyi"
author                     = "Angyi"
pygmentsuseclasses         = true


[permalinks]
  science                 = "science/:year-:month/:slug/"
  reading                   = "reading/:year-:month/:slug/"
  other                    = "other/:year-:month/:slug/"
  about                   = "about/:slug/"
  


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "归档"
    weight                 = 1
    identifier             = "archives"
    url                    = "archives/"  

  [[menu.main]]
    name                   = "代码"
    weight                 = 2
    identifier             = "science"
    url                    = "science/"  

  [[menu.main]]
    name                   = "读书"
    weight                 = 3
    identifier             = "reading"
    url                    = "reading/"  

  [[menu.main]]
    name                   = "生活"
    weight                 = 4
    identifier             = "other"
    url                    = "other/" 

  [[menu.main]]
    name                   = "关于"
    weight                 = 5
    identifier             = "about"
    url                    = "about/"  

 

[params]
  faviconfile              = "img/pig.png"               # from static/
  avatar                   = "img/1.jpg"             # path to image in static dir e.g img/avatar.png 
  author                   = "Angyi"
  description              = ["青岛 中国","星垂平野阔，月涌大江流","飘飘何所似，天地一沙鸥"]           # appears in the site header when set to a non-empty string
  welcome_head             = "最近动态!"
  #welcome_word             = "时间都去哪儿啦"

  latestpostscount         = 5                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "themes/AllinOne/static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  mainSections = ["science","reading","other"]

  # latex
  katex                    = true

  # busuanzi
  busuanzi = true
  busuanzi_site_offset = 100000

  # links
  email                    = "angyi_jq@163.com"
  github                   = "//github.com/Flionay"
  #linkedin                 = "//linkedin.com/in/you"
 # facebook                 = "//facebook.com/you"
 # googleplus               = "//google.com/you"
 # twitter                  = "//twitter.com/you" 
  px500                    = "//weibo.com/u/5792963723"
  instagram                = "//instagram.com/luckyflion"              
  include_rss              = true                          # include RSS <link> tag in <head> and show RSS icon
  
  # analytics
  googleAnalytics          = "your-google-analytic-id"

[params.valine]
  enable = true
  appId = 'GENPUwFk7J0C5AssHH1PfcOi-gzGzoHsz'
  appKey = 'NL8BdIcYfX3LwypstePGozwT'
  notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
  verify = false # Verification code
  avatar = 'mm' 
  placeholder = '请先编辑好上面的昵称和邮箱，然后说点什么吧...'
  visitor = true

